# 用Result处理可恢复的错误

```rs
enum Result<T, E> {
    Ok(T),
    Err(E)
}
```

通过打开文件场景，来处理成功和失败情况

```rs
use std::fs::File;

fn main() {
    let file_result = File::open("hello.txt");
}

```

`File::open`成功下，T是成功返回值的类型`std::fs::File`，是一个文件句柄

错误下，返回值类型是 `std::io::Error`


使用`match`处理`Result`成员

```rs
use std::fs::File;

fn main() {
    let file_result = File::open("hello.txt");

    let file = match file_result {
        Ok(file) => file,
        Err(error) => panic!("problem opening the file: {:?}", error),
    };
}
```